version: '3.8'

services:
  # 데이터베이스 설정
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: ieum_db
      POSTGRES_USER: hjxarchive
      POSTGRES_PASSWORD: "ieum2580-!"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data # 데이터 저장소 연결

  # 스프링 부트 앱 설정
  app:
    build: .
    container_name: spring-app
    #ports:
    #  - "8080:8080"
    depends_on:
      - db # DB가 먼저 뜬 후에 앱이 실행되도록 설정
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ieum_db
      SPRING_DATASOURCE_USERNAME: hjxarchive
      SPRING_DATASOURCE_PASSWORD: "ieum2580-!"
      GOOGLE_CLIENT_ID: 1088305482605-n4fnsouvlkf5md5ej2nllvpjuev666dd.apps.googleusercontent.com
      JWT_SECRET: 50Ykjh0ayk/ues8xTfAwJgvBpq27uR0rUrAq8tC89GBxoiiEhEPpQmkirUR2Twtu
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app