spring:
  application:
    name: ieum_back
  datasource:
    url: jdbc:postgresql://db:5432/ieum_db
    username: hjxarchive
    password: ieum2580-!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true